### ISSUE TITLE
[Bug] Tiles dont update when deleting a tile

### ISSUE THREAD

**Issue by stephenbush-wf** [maxwellpeterson-wf/GridHub#13]
When deleting a tile with the garbage-can button, the grid-tile titles appear to shift up and to the left in-order but the content in each grid-tile appears to remain the same as whatever tile used to occupy that location.  The buttons for switching the content type continue to function as well, toggling the different categories for the old repo.  Fixes on refresh.

Tested in Chrome 39.0.2171.95

**Comment by maxwellpeterson-wf** [comment]
This should be fixed with the new flux architecture
