### ISSUE TITLE
RC tags confuse the "unreleased merges" view?

### ISSUE THREAD

**Issue by chadknight-wf** [maxwellpeterson-wf/GridHub#15]
I'm not sure about my diagnosis in the description, but here's what I'm seeing:

![screen shot 2015-02-13 at 10 58 38 am](https://cloud.githubusercontent.com/assets/1737703/6191489/61c6f0ce-b36f-11e4-8cf3-146fcb1559ba.png)

those branches have been released in 0.2.1. there is a lingering 0.2.0 release candidate that is still in "pre-release" status, which seems to be the only unusual thing going on.

**Comment by maxwellpeterson-wf** [comment]
I believe we determined this to be the result of an RC tag that did not follow semver syntax. There isn't much I can do to account for tags that don't follow semver (except potentially ignore them, which we could discuss)
