### ISSUE TITLE
Hyperlink text flickers if user hovers near end of first line

### ISSUE THREAD

**Issue by aaronhoffman-wf** [maxwellpeterson-wf/GridHub#22]
If the text for a hyperlink is longer than one line, it is truncated. However if a user hovers over the link, all of the text is displayed and wraps over multiple lines. If this occurs, and a user hovers around the end of the first line, the hyperlink text will flicker.

screen capture:
(note: the refresh rate on this screen capture prevents this issue from being captured well, however if the actions are duplicated, you should see the issue on the live site)
http://screencast.com/t/PwgksVeL1y

**Comment by maxwellpeterson-wf** [comment]
Fixed in 0.4.0
