### ISSUE TITLE
Confusing Wording on Unreleased PRs 

### ISSUE THREAD

**Issue by chadknight-wf** [maxwellpeterson-wf/GridHub#40]
An unrleased PR will say something like "#69 closed 6 days ago by chadknight-wf". This reads like user chadknight-wf closed the PR 6 days ago, but it really means that #69, a PR by chadknight-wf, was closed 6 days ago.

Proposing change to "#69 by chadknight-wf - closed 6 days ago" or similar

**Comment by chadknight-wf** [comment]
thanks!

**Comment by maxwellpeterson-wf** [comment]
:+1:
